export default function Head() {
  return (
    <>
      <title>
        Md. Jamal Uddin - A passionate software engineer, a writer, and a mentor
        helping people to build products.
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
